[package]
name = "hfqr_recv"
version = "0.3.0"
edition = "2024"
authors = ["somewheve@gmail.com", "fakeshadow"]
description = "Trading order/market abstraction"
license = "MIT"


[dependencies]
serde_core = "1"
serde = { version = "1.0", features = ["derive"] }
